# Generated by Django 6.0.6 on 2026-07-04 06:16

import customer.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(choices=[('UPI', 'UPI'), ('COD', 'Cash on Delivery')], max_length=10)),
                ('upi_id', models.CharField(blank=True, max_length=50, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.sign')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackingId', models.CharField(default=customer.models.generate_trackingId, max_length=20, null=True, unique=True)),
                ('delivery_status', models.CharField(choices=[('PENDING', 'Pending'), ('AT_HUB', 'At Hub'), ('OUT_FOR_DELIVERY', 'Out For Delivery'), ('DEPARTED', 'Departed'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='Pending', max_length=50, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('status_updated_at', models.DateTimeField(blank=True, null=True)),
                ('current_location', models.CharField(max_length=50, null=True)),
                ('sender_name', models.CharField(max_length=100, null=True)),
                ('pickupAddress', models.TextField(null=True)),
                ('senderNumber', models.CharField(max_length=15, null=True)),
                ('recipientName', models.CharField(max_length=100, null=True)),
                ('recipientAddress', models.TextField(null=True)),
                ('recipientNumber', models.CharField(max_length=15, null=True)),
                ('package_description', models.CharField(max_length=100, null=True)),
                ('service_type', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('customerid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.sign')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.IntegerField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=30, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='static/invoices/')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.sign')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.shipment')),
            ],
        ),
    ]
