# Generated by Django 5.2.7 on 2025-10-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('pickupAddress', models.TextField(null=True)),
                ('senderNumber', models.IntegerField(null=True)),
                ('recipientName', models.CharField(max_length=100, null=True)),
                ('recipientAddress', models.TextField(null=True)),
                ('recipientNumber', models.IntegerField(null=True)),
                ('package', models.IntegerField(null=True)),
                ('service', models.CharField(choices=[('standard', 'Standard (3-5 days)'), ('express', 'Express (1-2 days)'), ('SameDay', 'Same Day')], max_length=100, null=True)),
                ('rs', models.CharField(max_length=10, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
