# Generated by Django 6.0.6 on 2026-07-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='current_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
