# Generated by Django 5.2.7 on 2025-10-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
