# Generated by Django 5.2.7 on 2025-10-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_booking_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, null=True)),
                ('answer', models.TextField(null=True)),
            ],
        ),
    ]
