# Generated by Django 5.2.7 on 2025-10-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='headingId',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
