# Generated by Django 5.2.7 on 2025-10-22 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_help_headingid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='help',
        ),
    ]
