# Generated by Django 5.2.7 on 2025-11-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_delete_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='deliveryDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(default='Pending', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='trackingId',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
