# Generated by Django 5.2.7 on 2025-11-05 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_booking_deliverydate_booking_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='deliveryDate',
            new_name='delivered_date',
        ),
    ]
