# Generated by Django 5.2.7 on 2025-12-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_rename_deliverydate_booking_delivered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='delivery_place_status',
            field=models.CharField(default='Pending', max_length=50, null=True),
        ),
    ]
