# Generated by Django 5.2.7 on 2025-12-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_booking_delivery_place_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reached_status_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='delivery_place_status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('out', 'out'), ('hub', 'hub'), ('depart', 'depart'), ('delivered', 'delivered')], default='Pending', max_length=50, null=True),
        ),
    ]
