# Generated by Django 5.2.7 on 2025-12-03 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_booking_reached_status_date_and_more'),
        ('main', '0007_sign_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='userid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.sign'),
        ),
    ]
