# Generated by Django 5.2.7 on 2025-12-04 11:32

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_booking_userid'),
        ('main', '0008_sign_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('out', 'out'), ('hub', 'hub'), ('depart', 'depart'), ('delivered', 'delivered'), ('cancelled', 'cancelled')], default='Pending', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='userid',
            field=models.ForeignKey(blank=True, default=main.models.sign, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.sign'),
        ),
    ]
