# Generated by Django 5.2.7 on 2025-12-04 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_invoice'),
        ('main', '0009_sign_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(choices=[('CARD', 'Card'), ('UPI', 'UPI'), ('COD', 'Cash on Delivery')], max_length=10)),
                ('brand', models.CharField(blank=True, max_length=20, null=True)),
                ('last4', models.CharField(blank=True, max_length=4, null=True)),
                ('upi_id', models.CharField(blank=True, max_length=50, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sign')),
            ],
        ),
    ]
