# Generated by Django 5.2.7 on 2025-12-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='static/invoices/'),
        ),
    ]
