# Generated by Django 5.2.7 on 2025-12-04 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_invoice_pdf'),
        ('main', '0009_sign_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='last4',
        ),
        migrations.AlterField(
            model_name='booking',
            name='userid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.sign'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='method_type',
            field=models.CharField(choices=[('UPI', 'UPI'), ('COD', 'Cash on Delivery')], max_length=10),
        ),
    ]
