# Generated by Django 5.2.7 on 2025-12-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_remove_paymentmethod_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.IntegerField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
