# Generated by Django 5.2.7 on 2025-12-08 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_reviewuser'),
        ('main', '0009_sign_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewuser',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.booking'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.booking'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.sign'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.sign'),
        ),
    ]
