# Generated by Django 5.2.7 on 2025-12-09 08:11

import customer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_reviewuser_booking_alter_invoice_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='trackingId',
            field=models.CharField(default=customer.models.generate_trackingId, max_length=20, null=True, unique=True),
        ),
    ]
