# Generated by Django 5.2.7 on 2025-12-11 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_alter_booking_trackingid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='package',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
