# Generated by Django 6.0.5 on 2026-05-17 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_alter_booking_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reviewuser',
            name='booking',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
        migrations.DeleteModel(
            name='ReviewUser',
        ),
    ]
