# Generated by Django 6.0.5 on 2026-05-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_remove_paymentmethod_user_remove_reviewuser_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='recipientNumber',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='rs',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='senderNumber',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('out', 'OUT_FOR_DELIVERY'), ('hub', 'AT_HUB'), ('depart', 'DEPARTED'), ('delivered', 'delivered'), ('cancelled', 'cancelled')], default='Pending', max_length=50, null=True),
        ),
    ]
