# Generated by Django 6.0.5 on 2026-05-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_alter_booking_date_alter_booking_recipientnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('out', 'OUT FOR DELIVERY'), ('hub', 'AT HUB'), ('depart', 'DEPARTED'), ('delivered', 'DELIVERED'), ('cancelled', 'CANCELLED')], default='Pending', max_length=50, null=True),
        ),
    ]
