# Generated by Django 6.0.5 on 2026-05-17 17:12

import customer.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0022_alter_booking_status'),
        ('main', '0009_sign_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackingId', models.CharField(default=customer.models.generate_trackingId, max_length=20, null=True, unique=True)),
                ('delivery_status', models.CharField(choices=[('PENDING', 'Pending'), ('AT_HUB', 'At Hub'), ('OUT_FOR_DELIVERY', 'Out For Delivery'), ('DEPARTED', 'Departed'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='Pending', max_length=50, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('status_updated_at', models.DateTimeField(blank=True, null=True)),
                ('current_location', models.CharField(max_length=50, null=True)),
                ('sender_name', models.CharField(max_length=100, null=True)),
                ('pickupAddress', models.TextField(null=True)),
                ('senderNumber', models.CharField(max_length=15, null=True)),
                ('recipientName', models.CharField(max_length=100, null=True)),
                ('recipientAddress', models.TextField(null=True)),
                ('recipientNumber', models.CharField(max_length=15, null=True)),
                ('package_description', models.CharField(max_length=100, null=True)),
                ('service_type', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('customerid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.sign')),
            ],
        ),
        migrations.DeleteModel(
            name='booking',
        ),
    ]
