# Generated by Django 6.0.6 on 2026-07-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('details', models.TextField(null=True)),
                ('address', models.TextField(null=True)),
                ('date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('address', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/userImage/')),
                ('mpass', models.CharField(max_length=100, null=True)),
                ('cpass', models.CharField(max_length=100, null=True)),
                ('date', models.DateTimeField(null=True)),
            ],
        ),
    ]
