# Generated by Django 5.1.7 on 2025-09-20 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contact_us',
        ),
    ]
