# Generated by Django 5.1.7 on 2025-09-25 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_contact_contact_us'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact_us',
        ),
        migrations.DeleteModel(
            name='Sign_up',
        ),
    ]
