# Generated by Django 5.1.7 on 2025-10-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
