# Generated by Django 5.1.7 on 2025-10-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_contactus_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sign',
            name='address',
        ),
        migrations.AddField(
            model_name='sign',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
