# Generated by Django 5.1.7 on 2025-10-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_sign_address_sign_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
