# Generated by Django 5.2.7 on 2025-12-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_sign_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
