# Generated by Django 5.2.7 on 2025-12-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_sign_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/userImage/'),
        ),
    ]
